name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build APK using Buildozer Docker
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: wifi-transfer-apk
          path: bin/*-debug.apk
